# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from visualization/radar_target.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class radar_target(genpy.Message):
  _md5sum = "fbd89b12a68c9a950a123efe1f1d5712"
  _type = "visualization/radar_target"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 seqID
uint32 RADARhwTimeStamp
float32[] rangeEstimate
float32[] velocityEstimate
float32[] amplitude

"""
  __slots__ = ['seqID','RADARhwTimeStamp','rangeEstimate','velocityEstimate','amplitude']
  _slot_types = ['uint32','uint32','float32[]','float32[]','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       seqID,RADARhwTimeStamp,rangeEstimate,velocityEstimate,amplitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(radar_target, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.seqID is None:
        self.seqID = 0
      if self.RADARhwTimeStamp is None:
        self.RADARhwTimeStamp = 0
      if self.rangeEstimate is None:
        self.rangeEstimate = []
      if self.velocityEstimate is None:
        self.velocityEstimate = []
      if self.amplitude is None:
        self.amplitude = []
    else:
      self.seqID = 0
      self.RADARhwTimeStamp = 0
      self.rangeEstimate = []
      self.velocityEstimate = []
      self.amplitude = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.seqID, _x.RADARhwTimeStamp))
      length = len(self.rangeEstimate)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.rangeEstimate))
      length = len(self.velocityEstimate)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.velocityEstimate))
      length = len(self.amplitude)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.amplitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.seqID, _x.RADARhwTimeStamp,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.rangeEstimate = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.velocityEstimate = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.amplitude = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.seqID, _x.RADARhwTimeStamp))
      length = len(self.rangeEstimate)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.rangeEstimate.tostring())
      length = len(self.velocityEstimate)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.velocityEstimate.tostring())
      length = len(self.amplitude)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.amplitude.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.seqID, _x.RADARhwTimeStamp,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.rangeEstimate = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.velocityEstimate = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.amplitude = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
