// Generated by gencpp from file iss_messages/fusion_overlay.msg
// DO NOT EDIT!


#ifndef ISS_MESSAGES_MESSAGE_FUSION_OVERLAY_H
#define ISS_MESSAGES_MESSAGE_FUSION_OVERLAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace iss_messages
{
template <class ContainerAllocator>
struct fusion_overlay_
{
  typedef fusion_overlay_<ContainerAllocator> Type;

  fusion_overlay_()
    : header()
    , image_feuertime()
    , fusionPoints()
    , range()  {
    }
  fusion_overlay_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_feuertime()
    , fusionPoints(_alloc)
    , range(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _image_feuertime_type;
  _image_feuertime_type image_feuertime;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _fusionPoints_type;
  _fusionPoints_type fusionPoints;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _range_type;
  _range_type range;




  typedef boost::shared_ptr< ::iss_messages::fusion_overlay_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iss_messages::fusion_overlay_<ContainerAllocator> const> ConstPtr;

}; // struct fusion_overlay_

typedef ::iss_messages::fusion_overlay_<std::allocator<void> > fusion_overlay;

typedef boost::shared_ptr< ::iss_messages::fusion_overlay > fusion_overlayPtr;
typedef boost::shared_ptr< ::iss_messages::fusion_overlay const> fusion_overlayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iss_messages::fusion_overlay_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iss_messages::fusion_overlay_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iss_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'iss_messages': ['/home/feuerwerr/Repository/feuerwerr_ros/trunk/catkin_ws/src/iss_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iss_messages::fusion_overlay_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iss_messages::fusion_overlay_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iss_messages::fusion_overlay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iss_messages::fusion_overlay_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iss_messages::fusion_overlay_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iss_messages::fusion_overlay_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iss_messages::fusion_overlay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df8e1f6b30f762c4e9c76e7e87f4cfef";
  }

  static const char* value(const ::iss_messages::fusion_overlay_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf8e1f6b30f762c4ULL;
  static const uint64_t static_value2 = 0xe9c76e7e87f4cfefULL;
};

template<class ContainerAllocator>
struct DataType< ::iss_messages::fusion_overlay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iss_messages/fusion_overlay";
  }

  static const char* value(const ::iss_messages::fusion_overlay_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iss_messages::fusion_overlay_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
time image_feuertime\n\
\n\
float32[] fusionPoints\n\
float32[] range\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::iss_messages::fusion_overlay_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iss_messages::fusion_overlay_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_feuertime);
      stream.next(m.fusionPoints);
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fusion_overlay_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iss_messages::fusion_overlay_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iss_messages::fusion_overlay_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_feuertime: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.image_feuertime);
    s << indent << "fusionPoints[]" << std::endl;
    for (size_t i = 0; i < v.fusionPoints.size(); ++i)
    {
      s << indent << "  fusionPoints[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.fusionPoints[i]);
    }
    s << indent << "range[]" << std::endl;
    for (size_t i = 0; i < v.range.size(); ++i)
    {
      s << indent << "  range[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.range[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISS_MESSAGES_MESSAGE_FUSION_OVERLAY_H
