// Generated by gencpp from file iss_messages/radar_target.msg
// DO NOT EDIT!


#ifndef ISS_MESSAGES_MESSAGE_RADAR_TARGET_H
#define ISS_MESSAGES_MESSAGE_RADAR_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace iss_messages
{
template <class ContainerAllocator>
struct radar_target_
{
  typedef radar_target_<ContainerAllocator> Type;

  radar_target_()
    : header()
    , radar_feuertime()
    , rangeEstimate()
    , velocityEstimate()
    , amplitude()  {
    }
  radar_target_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , radar_feuertime()
    , rangeEstimate(_alloc)
    , velocityEstimate(_alloc)
    , amplitude(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _radar_feuertime_type;
  _radar_feuertime_type radar_feuertime;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _rangeEstimate_type;
  _rangeEstimate_type rangeEstimate;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _velocityEstimate_type;
  _velocityEstimate_type velocityEstimate;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _amplitude_type;
  _amplitude_type amplitude;




  typedef boost::shared_ptr< ::iss_messages::radar_target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iss_messages::radar_target_<ContainerAllocator> const> ConstPtr;

}; // struct radar_target_

typedef ::iss_messages::radar_target_<std::allocator<void> > radar_target;

typedef boost::shared_ptr< ::iss_messages::radar_target > radar_targetPtr;
typedef boost::shared_ptr< ::iss_messages::radar_target const> radar_targetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iss_messages::radar_target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iss_messages::radar_target_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iss_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'iss_messages': ['/home/feuerwerr/Repository/feuerwerr_ros/trunk/catkin_ws/src/iss_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iss_messages::radar_target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iss_messages::radar_target_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iss_messages::radar_target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iss_messages::radar_target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iss_messages::radar_target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iss_messages::radar_target_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iss_messages::radar_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76fe86515993ef411b4797c8ff5dbde8";
  }

  static const char* value(const ::iss_messages::radar_target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76fe86515993ef41ULL;
  static const uint64_t static_value2 = 0x1b4797c8ff5dbde8ULL;
};

template<class ContainerAllocator>
struct DataType< ::iss_messages::radar_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iss_messages/radar_target";
  }

  static const char* value(const ::iss_messages::radar_target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iss_messages::radar_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
time radar_feuertime\n\
\n\
float32[] rangeEstimate\n\
float32[] velocityEstimate\n\
float32[] amplitude\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::iss_messages::radar_target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iss_messages::radar_target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.radar_feuertime);
      stream.next(m.rangeEstimate);
      stream.next(m.velocityEstimate);
      stream.next(m.amplitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iss_messages::radar_target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iss_messages::radar_target_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "radar_feuertime: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.radar_feuertime);
    s << indent << "rangeEstimate[]" << std::endl;
    for (size_t i = 0; i < v.rangeEstimate.size(); ++i)
    {
      s << indent << "  rangeEstimate[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rangeEstimate[i]);
    }
    s << indent << "velocityEstimate[]" << std::endl;
    for (size_t i = 0; i < v.velocityEstimate.size(); ++i)
    {
      s << indent << "  velocityEstimate[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocityEstimate[i]);
    }
    s << indent << "amplitude[]" << std::endl;
    for (size_t i = 0; i < v.amplitude.size(); ++i)
    {
      s << indent << "  amplitude[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.amplitude[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISS_MESSAGES_MESSAGE_RADAR_TARGET_H
