(cl:defpackage visualization-srv
  (:use )
  (:export
   "AUTOFLAG"
   "<AUTOFLAG-REQUEST>"
   "AUTOFLAG-REQUEST"
   "<AUTOFLAG-RESPONSE>"
   "AUTOFLAG-RESPONSE"
   "PALETTE"
   "<PALETTE-REQUEST>"
   "PALETTE-REQUEST"
   "<PALETTE-RESPONSE>"
   "PALETTE-RESPONSE"
   "TEMPERATURERANGE"
   "<TEMPERATURERANGE-REQUEST>"
   "TEMPERATURERANGE-REQUEST"
   "<TEMPERATURERANGE-RESPONSE>"
   "TEMPERATURERANGE-RESPONSE"
  ))

