classdef PaletteRequest < robotics.ros.Message
    %PaletteRequest MATLAB implementation of optris_drivers/PaletteRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'optris_drivers/PaletteRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'f28136ebeed4771c7945cbcc0527c8c0' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Palette
        PaletteScaling
        TemperatureMin
        TemperatureMax
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Palette', 'PaletteScaling', 'TemperatureMax', 'TemperatureMin'} % List of non-constant message properties
        ROSPropertyList = {'palette', 'paletteScaling', 'temperatureMax', 'temperatureMin'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = PaletteRequest(msg)
            %PaletteRequest Construct the message object PaletteRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function palette = get.Palette(obj)
            %get.Palette Get the value for property Palette
            palette = int16(obj.JavaMessage.getPalette);
        end
        
        function set.Palette(obj, palette)
            %set.Palette Set the value for property Palette
            validateattributes(palette, {'numeric'}, {'nonempty', 'scalar'}, 'PaletteRequest', 'Palette');
            
            obj.JavaMessage.setPalette(palette);
        end
        
        function palettescaling = get.PaletteScaling(obj)
            %get.PaletteScaling Get the value for property PaletteScaling
            palettescaling = int16(obj.JavaMessage.getPaletteScaling);
        end
        
        function set.PaletteScaling(obj, palettescaling)
            %set.PaletteScaling Set the value for property PaletteScaling
            validateattributes(palettescaling, {'numeric'}, {'nonempty', 'scalar'}, 'PaletteRequest', 'PaletteScaling');
            
            obj.JavaMessage.setPaletteScaling(palettescaling);
        end
        
        function temperaturemin = get.TemperatureMin(obj)
            %get.TemperatureMin Get the value for property TemperatureMin
            temperaturemin = single(obj.JavaMessage.getTemperatureMin);
        end
        
        function set.TemperatureMin(obj, temperaturemin)
            %set.TemperatureMin Set the value for property TemperatureMin
            validateattributes(temperaturemin, {'numeric'}, {'nonempty', 'scalar'}, 'PaletteRequest', 'TemperatureMin');
            
            obj.JavaMessage.setTemperatureMin(temperaturemin);
        end
        
        function temperaturemax = get.TemperatureMax(obj)
            %get.TemperatureMax Get the value for property TemperatureMax
            temperaturemax = single(obj.JavaMessage.getTemperatureMax);
        end
        
        function set.TemperatureMax(obj, temperaturemax)
            %set.TemperatureMax Set the value for property TemperatureMax
            validateattributes(temperaturemax, {'numeric'}, {'nonempty', 'scalar'}, 'PaletteRequest', 'TemperatureMax');
            
            obj.JavaMessage.setTemperatureMax(temperaturemax);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Palette = obj.Palette;
            cpObj.PaletteScaling = obj.PaletteScaling;
            cpObj.TemperatureMin = obj.TemperatureMin;
            cpObj.TemperatureMax = obj.TemperatureMax;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Palette = strObj.Palette;
            obj.PaletteScaling = strObj.PaletteScaling;
            obj.TemperatureMin = strObj.TemperatureMin;
            obj.TemperatureMax = strObj.TemperatureMax;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Palette = obj.Palette;
            strObj.PaletteScaling = obj.PaletteScaling;
            strObj.TemperatureMin = obj.TemperatureMin;
            strObj.TemperatureMax = obj.TemperatureMax;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.optris_drivers.PaletteRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.optris_drivers.PaletteRequest;
            obj.reload(strObj);
        end
    end
end
