// Generated by gencpp from file sensor_synch_drivers/FeuerWeRRStartAquistionRequest.msg
// DO NOT EDIT!


#ifndef SENSOR_SYNCH_DRIVERS_MESSAGE_FEUERWERRSTARTAQUISTIONREQUEST_H
#define SENSOR_SYNCH_DRIVERS_MESSAGE_FEUERWERRSTARTAQUISTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sensor_synch_drivers
{
template <class ContainerAllocator>
struct FeuerWeRRStartAquistionRequest_
{
  typedef FeuerWeRRStartAquistionRequest_<ContainerAllocator> Type;

  FeuerWeRRStartAquistionRequest_()
    : header()
    , radar_start(false)
    , ir_start(false)  {
    }
  FeuerWeRRStartAquistionRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , radar_start(false)
    , ir_start(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _radar_start_type;
  _radar_start_type radar_start;

   typedef uint8_t _ir_start_type;
  _ir_start_type ir_start;




  typedef boost::shared_ptr< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FeuerWeRRStartAquistionRequest_

typedef ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<std::allocator<void> > FeuerWeRRStartAquistionRequest;

typedef boost::shared_ptr< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest > FeuerWeRRStartAquistionRequestPtr;
typedef boost::shared_ptr< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest const> FeuerWeRRStartAquistionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_synch_drivers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_synch_drivers': ['/home/feuerwerr/Repository/feuerwerr_ros/trunk/catkin_ws/src/sensor_synch_drivers/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a148093116093404300600142971a26c";
  }

  static const char* value(const ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa148093116093404ULL;
  static const uint64_t static_value2 = 0x300600142971a26cULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_synch_drivers/FeuerWeRRStartAquistionRequest";
  }

  static const char* value(const ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool radar_start\n\
bool ir_start\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.radar_start);
      stream.next(m.ir_start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FeuerWeRRStartAquistionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_synch_drivers::FeuerWeRRStartAquistionRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "radar_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radar_start);
    s << indent << "ir_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ir_start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_SYNCH_DRIVERS_MESSAGE_FEUERWERRSTARTAQUISTIONREQUEST_H
