// Generated by gencpp from file visualization/AutoFlag.msg
// DO NOT EDIT!


#ifndef VISUALIZATION_MESSAGE_AUTOFLAG_H
#define VISUALIZATION_MESSAGE_AUTOFLAG_H

#include <ros/service_traits.h>


#include <visualization/AutoFlagRequest.h>
#include <visualization/AutoFlagResponse.h>


namespace visualization
{

struct AutoFlag
{

typedef AutoFlagRequest Request;
typedef AutoFlagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AutoFlag
} // namespace visualization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::visualization::AutoFlag > {
  static const char* value()
  {
    return "c55e7efaaabffa6dd063014d83eca6d2";
  }

  static const char* value(const ::visualization::AutoFlag&) { return value(); }
};

template<>
struct DataType< ::visualization::AutoFlag > {
  static const char* value()
  {
    return "visualization/AutoFlag";
  }

  static const char* value(const ::visualization::AutoFlag&) { return value(); }
};


// service_traits::MD5Sum< ::visualization::AutoFlagRequest> should match 
// service_traits::MD5Sum< ::visualization::AutoFlag > 
template<>
struct MD5Sum< ::visualization::AutoFlagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::visualization::AutoFlag >::value();
  }
  static const char* value(const ::visualization::AutoFlagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::visualization::AutoFlagRequest> should match 
// service_traits::DataType< ::visualization::AutoFlag > 
template<>
struct DataType< ::visualization::AutoFlagRequest>
{
  static const char* value()
  {
    return DataType< ::visualization::AutoFlag >::value();
  }
  static const char* value(const ::visualization::AutoFlagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::visualization::AutoFlagResponse> should match 
// service_traits::MD5Sum< ::visualization::AutoFlag > 
template<>
struct MD5Sum< ::visualization::AutoFlagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::visualization::AutoFlag >::value();
  }
  static const char* value(const ::visualization::AutoFlagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::visualization::AutoFlagResponse> should match 
// service_traits::DataType< ::visualization::AutoFlag > 
template<>
struct DataType< ::visualization::AutoFlagResponse>
{
  static const char* value()
  {
    return DataType< ::visualization::AutoFlag >::value();
  }
  static const char* value(const ::visualization::AutoFlagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISUALIZATION_MESSAGE_AUTOFLAG_H
