// Generated by gencpp from file visualization/radar_target.msg
// DO NOT EDIT!


#ifndef VISUALIZATION_MESSAGE_RADAR_TARGET_H
#define VISUALIZATION_MESSAGE_RADAR_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visualization
{
template <class ContainerAllocator>
struct radar_target_
{
  typedef radar_target_<ContainerAllocator> Type;

  radar_target_()
    : seqID(0)
    , RADARhwTimeStamp(0)
    , rangeEstimate()
    , velocityEstimate()
    , amplitude()  {
    }
  radar_target_(const ContainerAllocator& _alloc)
    : seqID(0)
    , RADARhwTimeStamp(0)
    , rangeEstimate(_alloc)
    , velocityEstimate(_alloc)
    , amplitude(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _seqID_type;
  _seqID_type seqID;

   typedef uint32_t _RADARhwTimeStamp_type;
  _RADARhwTimeStamp_type RADARhwTimeStamp;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _rangeEstimate_type;
  _rangeEstimate_type rangeEstimate;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _velocityEstimate_type;
  _velocityEstimate_type velocityEstimate;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _amplitude_type;
  _amplitude_type amplitude;




  typedef boost::shared_ptr< ::visualization::radar_target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visualization::radar_target_<ContainerAllocator> const> ConstPtr;

}; // struct radar_target_

typedef ::visualization::radar_target_<std::allocator<void> > radar_target;

typedef boost::shared_ptr< ::visualization::radar_target > radar_targetPtr;
typedef boost::shared_ptr< ::visualization::radar_target const> radar_targetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visualization::radar_target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visualization::radar_target_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visualization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'visualization': ['/home/feuerwerr/Repository/feuerwerr_ros/trunk/catkin_ws/src/visualization/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visualization::radar_target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visualization::radar_target_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visualization::radar_target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visualization::radar_target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualization::radar_target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visualization::radar_target_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visualization::radar_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbd89b12a68c9a950a123efe1f1d5712";
  }

  static const char* value(const ::visualization::radar_target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbd89b12a68c9a95ULL;
  static const uint64_t static_value2 = 0x0a123efe1f1d5712ULL;
};

template<class ContainerAllocator>
struct DataType< ::visualization::radar_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visualization/radar_target";
  }

  static const char* value(const ::visualization::radar_target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visualization::radar_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 seqID\n\
uint32 RADARhwTimeStamp\n\
float32[] rangeEstimate\n\
float32[] velocityEstimate\n\
float32[] amplitude\n\
\n\
";
  }

  static const char* value(const ::visualization::radar_target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visualization::radar_target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seqID);
      stream.next(m.RADARhwTimeStamp);
      stream.next(m.rangeEstimate);
      stream.next(m.velocityEstimate);
      stream.next(m.amplitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radar_target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visualization::radar_target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visualization::radar_target_<ContainerAllocator>& v)
  {
    s << indent << "seqID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seqID);
    s << indent << "RADARhwTimeStamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.RADARhwTimeStamp);
    s << indent << "rangeEstimate[]" << std::endl;
    for (size_t i = 0; i < v.rangeEstimate.size(); ++i)
    {
      s << indent << "  rangeEstimate[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rangeEstimate[i]);
    }
    s << indent << "velocityEstimate[]" << std::endl;
    for (size_t i = 0; i < v.velocityEstimate.size(); ++i)
    {
      s << indent << "  velocityEstimate[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocityEstimate[i]);
    }
    s << indent << "amplitude[]" << std::endl;
    for (size_t i = 0; i < v.amplitude.size(); ++i)
    {
      s << indent << "  amplitude[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.amplitude[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUALIZATION_MESSAGE_RADAR_TARGET_H
