(cl:defpackage sensor_synch_drivers-srv
  (:use )
  (:export
   "FEUERWERRSTARTAQUISTION"
   "<FEUERWERRSTARTAQUISTION-REQUEST>"
   "FEUERWERRSTARTAQUISTION-REQUEST"
   "<FEUERWERRSTARTAQUISTION-RESPONSE>"
   "FEUERWERRSTARTAQUISTION-RESPONSE"
  ))

