// Generated by gencpp from file optris_drivers/AutoFlag.msg
// DO NOT EDIT!


#ifndef OPTRIS_DRIVERS_MESSAGE_AUTOFLAG_H
#define OPTRIS_DRIVERS_MESSAGE_AUTOFLAG_H

#include <ros/service_traits.h>


#include <optris_drivers/AutoFlagRequest.h>
#include <optris_drivers/AutoFlagResponse.h>


namespace optris_drivers
{

struct AutoFlag
{

typedef AutoFlagRequest Request;
typedef AutoFlagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AutoFlag
} // namespace optris_drivers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optris_drivers::AutoFlag > {
  static const char* value()
  {
    return "c55e7efaaabffa6dd063014d83eca6d2";
  }

  static const char* value(const ::optris_drivers::AutoFlag&) { return value(); }
};

template<>
struct DataType< ::optris_drivers::AutoFlag > {
  static const char* value()
  {
    return "optris_drivers/AutoFlag";
  }

  static const char* value(const ::optris_drivers::AutoFlag&) { return value(); }
};


// service_traits::MD5Sum< ::optris_drivers::AutoFlagRequest> should match 
// service_traits::MD5Sum< ::optris_drivers::AutoFlag > 
template<>
struct MD5Sum< ::optris_drivers::AutoFlagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optris_drivers::AutoFlag >::value();
  }
  static const char* value(const ::optris_drivers::AutoFlagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optris_drivers::AutoFlagRequest> should match 
// service_traits::DataType< ::optris_drivers::AutoFlag > 
template<>
struct DataType< ::optris_drivers::AutoFlagRequest>
{
  static const char* value()
  {
    return DataType< ::optris_drivers::AutoFlag >::value();
  }
  static const char* value(const ::optris_drivers::AutoFlagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optris_drivers::AutoFlagResponse> should match 
// service_traits::MD5Sum< ::optris_drivers::AutoFlag > 
template<>
struct MD5Sum< ::optris_drivers::AutoFlagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optris_drivers::AutoFlag >::value();
  }
  static const char* value(const ::optris_drivers::AutoFlagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optris_drivers::AutoFlagResponse> should match 
// service_traits::DataType< ::optris_drivers::AutoFlag > 
template<>
struct DataType< ::optris_drivers::AutoFlagResponse>
{
  static const char* value()
  {
    return DataType< ::optris_drivers::AutoFlag >::value();
  }
  static const char* value(const ::optris_drivers::AutoFlagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTRIS_DRIVERS_MESSAGE_AUTOFLAG_H
