// Generated by gencpp from file optris_drivers/Palette.msg
// DO NOT EDIT!


#ifndef OPTRIS_DRIVERS_MESSAGE_PALETTE_H
#define OPTRIS_DRIVERS_MESSAGE_PALETTE_H

#include <ros/service_traits.h>


#include <optris_drivers/PaletteRequest.h>
#include <optris_drivers/PaletteResponse.h>


namespace optris_drivers
{

struct Palette
{

typedef PaletteRequest Request;
typedef PaletteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Palette
} // namespace optris_drivers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optris_drivers::Palette > {
  static const char* value()
  {
    return "cd6f35b272f9ce0ceb0409de9795cd7f";
  }

  static const char* value(const ::optris_drivers::Palette&) { return value(); }
};

template<>
struct DataType< ::optris_drivers::Palette > {
  static const char* value()
  {
    return "optris_drivers/Palette";
  }

  static const char* value(const ::optris_drivers::Palette&) { return value(); }
};


// service_traits::MD5Sum< ::optris_drivers::PaletteRequest> should match 
// service_traits::MD5Sum< ::optris_drivers::Palette > 
template<>
struct MD5Sum< ::optris_drivers::PaletteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optris_drivers::Palette >::value();
  }
  static const char* value(const ::optris_drivers::PaletteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optris_drivers::PaletteRequest> should match 
// service_traits::DataType< ::optris_drivers::Palette > 
template<>
struct DataType< ::optris_drivers::PaletteRequest>
{
  static const char* value()
  {
    return DataType< ::optris_drivers::Palette >::value();
  }
  static const char* value(const ::optris_drivers::PaletteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optris_drivers::PaletteResponse> should match 
// service_traits::MD5Sum< ::optris_drivers::Palette > 
template<>
struct MD5Sum< ::optris_drivers::PaletteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optris_drivers::Palette >::value();
  }
  static const char* value(const ::optris_drivers::PaletteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optris_drivers::PaletteResponse> should match 
// service_traits::DataType< ::optris_drivers::Palette > 
template<>
struct DataType< ::optris_drivers::PaletteResponse>
{
  static const char* value()
  {
    return DataType< ::optris_drivers::Palette >::value();
  }
  static const char* value(const ::optris_drivers::PaletteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTRIS_DRIVERS_MESSAGE_PALETTE_H
