// Generated by gencpp from file optris_drivers/PaletteResponse.msg
// DO NOT EDIT!


#ifndef OPTRIS_DRIVERS_MESSAGE_PALETTERESPONSE_H
#define OPTRIS_DRIVERS_MESSAGE_PALETTERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace optris_drivers
{
template <class ContainerAllocator>
struct PaletteResponse_
{
  typedef PaletteResponse_<ContainerAllocator> Type;

  PaletteResponse_()
    : success(false)  {
    }
  PaletteResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::optris_drivers::PaletteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optris_drivers::PaletteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PaletteResponse_

typedef ::optris_drivers::PaletteResponse_<std::allocator<void> > PaletteResponse;

typedef boost::shared_ptr< ::optris_drivers::PaletteResponse > PaletteResponsePtr;
typedef boost::shared_ptr< ::optris_drivers::PaletteResponse const> PaletteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optris_drivers::PaletteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optris_drivers::PaletteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace optris_drivers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'optris_drivers': ['/home/feuerwerr/Repository/feuerwerr_ros/trunk/catkin_ws/src/optris_drivers/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::optris_drivers::PaletteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optris_drivers::PaletteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optris_drivers::PaletteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optris_drivers::PaletteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optris_drivers::PaletteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optris_drivers::PaletteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optris_drivers::PaletteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::optris_drivers::PaletteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::optris_drivers::PaletteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optris_drivers/PaletteResponse";
  }

  static const char* value(const ::optris_drivers::PaletteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optris_drivers::PaletteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const ::optris_drivers::PaletteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optris_drivers::PaletteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PaletteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optris_drivers::PaletteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optris_drivers::PaletteResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTRIS_DRIVERS_MESSAGE_PALETTERESPONSE_H
