// Generated by gencpp from file optris_drivers/TemperatureRange.msg
// DO NOT EDIT!


#ifndef OPTRIS_DRIVERS_MESSAGE_TEMPERATURERANGE_H
#define OPTRIS_DRIVERS_MESSAGE_TEMPERATURERANGE_H

#include <ros/service_traits.h>


#include <optris_drivers/TemperatureRangeRequest.h>
#include <optris_drivers/TemperatureRangeResponse.h>


namespace optris_drivers
{

struct TemperatureRange
{

typedef TemperatureRangeRequest Request;
typedef TemperatureRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TemperatureRange
} // namespace optris_drivers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::optris_drivers::TemperatureRange > {
  static const char* value()
  {
    return "10eabfbcf8caad5dbfe2a7ee7be8570f";
  }

  static const char* value(const ::optris_drivers::TemperatureRange&) { return value(); }
};

template<>
struct DataType< ::optris_drivers::TemperatureRange > {
  static const char* value()
  {
    return "optris_drivers/TemperatureRange";
  }

  static const char* value(const ::optris_drivers::TemperatureRange&) { return value(); }
};


// service_traits::MD5Sum< ::optris_drivers::TemperatureRangeRequest> should match 
// service_traits::MD5Sum< ::optris_drivers::TemperatureRange > 
template<>
struct MD5Sum< ::optris_drivers::TemperatureRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::optris_drivers::TemperatureRange >::value();
  }
  static const char* value(const ::optris_drivers::TemperatureRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::optris_drivers::TemperatureRangeRequest> should match 
// service_traits::DataType< ::optris_drivers::TemperatureRange > 
template<>
struct DataType< ::optris_drivers::TemperatureRangeRequest>
{
  static const char* value()
  {
    return DataType< ::optris_drivers::TemperatureRange >::value();
  }
  static const char* value(const ::optris_drivers::TemperatureRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::optris_drivers::TemperatureRangeResponse> should match 
// service_traits::MD5Sum< ::optris_drivers::TemperatureRange > 
template<>
struct MD5Sum< ::optris_drivers::TemperatureRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::optris_drivers::TemperatureRange >::value();
  }
  static const char* value(const ::optris_drivers::TemperatureRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::optris_drivers::TemperatureRangeResponse> should match 
// service_traits::DataType< ::optris_drivers::TemperatureRange > 
template<>
struct DataType< ::optris_drivers::TemperatureRangeResponse>
{
  static const char* value()
  {
    return DataType< ::optris_drivers::TemperatureRange >::value();
  }
  static const char* value(const ::optris_drivers::TemperatureRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPTRIS_DRIVERS_MESSAGE_TEMPERATURERANGE_H
